# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {}

modules = []

doc_url = "https://Daniel-R-Armstrong.github.io/medcast/"

git_url = "https://github.com/Daniel-R-Armstrong/medcast/tree/master/"

def custom_doc_links(name): return None
